"""Included function to display creator of posts

Revision ID: 34daa97ed89e
Revises: efd5c78cb3c1
Create Date: 2021-11-25 23:48:22.618706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34daa97ed89e'
down_revision = 'efd5c78cb3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'flasklogin-users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'creator_id')
    # ### end Alembic commands ###
