"""Fix 2

Revision ID: 6736d0977bc7
Revises: 71dc3bbc606f
Create Date: 2021-12-16 14:05:52.184686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6736d0977bc7'
down_revision = '71dc3bbc606f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('message', sa.String(length=2000), nullable=False))
    op.drop_column('replies', 'reply_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('reply_content', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.drop_column('replies', 'message')
    # ### end Alembic commands ###
