"""Added replply databse

Revision ID: 71dc3bbc606f
Revises: 21fa41156aeb
Create Date: 2021-12-16 11:46:17.948223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dc3bbc606f'
down_revision = '21fa41156aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('reply_content', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('reply_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    # ### end Alembic commands ###
