"""new initial migration

Revision ID: c7ae89f704bc
Revises: 
Create Date: 2021-12-17 12:24:49.042169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ae89f704bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=80), nullable=False),
    sa.Column('post_content', sa.String(length=500), server_default='No description provided...', nullable=True),
    sa.Column('ranked_importance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['flasklogin-users.id'], ),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('post_title')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('commentor_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commentor_id'], ['flasklogin-users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('following',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flasklogin-users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('following')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('flasklogin-users')
    # ### end Alembic commands ###
