"""Edited models to add new post content

Revision ID: d2592b5fafe0
Revises: 53a3bbd813ac
Create Date: 2021-11-23 22:58:46.545714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2592b5fafe0'
down_revision = '53a3bbd813ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_content', sa.String(length=200), server_default='No description provided...', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_content')
    # ### end Alembic commands ###
