"""new initial migration

Revision ID: efd5c78cb3c1
Revises: 
Create Date: 2021-11-24 22:38:59.845754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd5c78cb3c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=80), nullable=False),
    sa.Column('post_content', sa.String(length=500), server_default='No description provided...', nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('post_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('flasklogin-users')
    # ### end Alembic commands ###
